/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CoachIndexRouteImport } from './routes/coach.index'
import { Route as AnalysisIndexRouteImport } from './routes/analysis.index'
import { Route as ProfileWeightRouteImport } from './routes/profile.weight'
import { Route as ProfileNudgesRouteImport } from './routes/profile.nudges'
import { Route as ProfileHistoryRouteImport } from './routes/profile.history'
import { Route as ProfileGoalsRouteImport } from './routes/profile.goals'
import { Route as ProfileAchievementsRouteImport } from './routes/profile.achievements'
import { Route as OnboardingReassessRouteImport } from './routes/onboarding.reassess'
import { Route as CommunityCreateRouteImport } from './routes/community.create'
import { Route as CommunityEventIdRouteImport } from './routes/community.$eventId'
import { Route as CoachChatRouteImport } from './routes/coach.chat'
import { Route as AnalysisResultRouteImport } from './routes/analysis.result'
import { Route as CoachWorkoutSessionIdIndexRouteImport } from './routes/coach.workout.$sessionId.index'
import { Route as CoachWorkoutSessionIdDoneRouteImport } from './routes/coach.workout.$sessionId.done'

const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachIndexRoute = CoachIndexRouteImport.update({
  id: '/coach/',
  path: '/coach/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/analysis/',
  path: '/analysis/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileWeightRoute = ProfileWeightRouteImport.update({
  id: '/profile/weight',
  path: '/profile/weight',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileNudgesRoute = ProfileNudgesRouteImport.update({
  id: '/profile/nudges',
  path: '/profile/nudges',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHistoryRoute = ProfileHistoryRouteImport.update({
  id: '/profile/history',
  path: '/profile/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileGoalsRoute = ProfileGoalsRouteImport.update({
  id: '/profile/goals',
  path: '/profile/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAchievementsRoute = ProfileAchievementsRouteImport.update({
  id: '/profile/achievements',
  path: '/profile/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingReassessRoute = OnboardingReassessRouteImport.update({
  id: '/reassess',
  path: '/reassess',
  getParentRoute: () => OnboardingRoute,
} as any)
const CommunityCreateRoute = CommunityCreateRouteImport.update({
  id: '/community/create',
  path: '/community/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityEventIdRoute = CommunityEventIdRouteImport.update({
  id: '/community/$eventId',
  path: '/community/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachChatRoute = CoachChatRouteImport.update({
  id: '/coach/chat',
  path: '/coach/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisResultRoute = AnalysisResultRouteImport.update({
  id: '/analysis/result',
  path: '/analysis/result',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachWorkoutSessionIdIndexRoute =
  CoachWorkoutSessionIdIndexRouteImport.update({
    id: '/coach/workout/$sessionId/',
    path: '/coach/workout/$sessionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoachWorkoutSessionIdDoneRoute =
  CoachWorkoutSessionIdDoneRouteImport.update({
    id: '/coach/workout/$sessionId/done',
    path: '/coach/workout/$sessionId/done',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signup': typeof SignupRoute
  '/tutorial': typeof TutorialRoute
  '/analysis/result': typeof AnalysisResultRoute
  '/coach/chat': typeof CoachChatRoute
  '/community/$eventId': typeof CommunityEventIdRoute
  '/community/create': typeof CommunityCreateRoute
  '/onboarding/reassess': typeof OnboardingReassessRoute
  '/profile/achievements': typeof ProfileAchievementsRoute
  '/profile/goals': typeof ProfileGoalsRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/nudges': typeof ProfileNudgesRoute
  '/profile/weight': typeof ProfileWeightRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/coach/workout/$sessionId/done': typeof CoachWorkoutSessionIdDoneRoute
  '/coach/workout/$sessionId/': typeof CoachWorkoutSessionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signup': typeof SignupRoute
  '/tutorial': typeof TutorialRoute
  '/analysis/result': typeof AnalysisResultRoute
  '/coach/chat': typeof CoachChatRoute
  '/community/$eventId': typeof CommunityEventIdRoute
  '/community/create': typeof CommunityCreateRoute
  '/onboarding/reassess': typeof OnboardingReassessRoute
  '/profile/achievements': typeof ProfileAchievementsRoute
  '/profile/goals': typeof ProfileGoalsRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/nudges': typeof ProfileNudgesRoute
  '/profile/weight': typeof ProfileWeightRoute
  '/analysis': typeof AnalysisIndexRoute
  '/coach': typeof CoachIndexRoute
  '/community': typeof CommunityIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/coach/workout/$sessionId/done': typeof CoachWorkoutSessionIdDoneRoute
  '/coach/workout/$sessionId': typeof CoachWorkoutSessionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/signup': typeof SignupRoute
  '/tutorial': typeof TutorialRoute
  '/analysis/result': typeof AnalysisResultRoute
  '/coach/chat': typeof CoachChatRoute
  '/community/$eventId': typeof CommunityEventIdRoute
  '/community/create': typeof CommunityCreateRoute
  '/onboarding/reassess': typeof OnboardingReassessRoute
  '/profile/achievements': typeof ProfileAchievementsRoute
  '/profile/goals': typeof ProfileGoalsRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/nudges': typeof ProfileNudgesRoute
  '/profile/weight': typeof ProfileWeightRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/coach/': typeof CoachIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/coach/workout/$sessionId/done': typeof CoachWorkoutSessionIdDoneRoute
  '/coach/workout/$sessionId/': typeof CoachWorkoutSessionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/tutorial'
    | '/analysis/result'
    | '/coach/chat'
    | '/community/$eventId'
    | '/community/create'
    | '/onboarding/reassess'
    | '/profile/achievements'
    | '/profile/goals'
    | '/profile/history'
    | '/profile/nudges'
    | '/profile/weight'
    | '/analysis/'
    | '/coach/'
    | '/community/'
    | '/profile/'
    | '/coach/workout/$sessionId/done'
    | '/coach/workout/$sessionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/tutorial'
    | '/analysis/result'
    | '/coach/chat'
    | '/community/$eventId'
    | '/community/create'
    | '/onboarding/reassess'
    | '/profile/achievements'
    | '/profile/goals'
    | '/profile/history'
    | '/profile/nudges'
    | '/profile/weight'
    | '/analysis'
    | '/coach'
    | '/community'
    | '/profile'
    | '/coach/workout/$sessionId/done'
    | '/coach/workout/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/tutorial'
    | '/analysis/result'
    | '/coach/chat'
    | '/community/$eventId'
    | '/community/create'
    | '/onboarding/reassess'
    | '/profile/achievements'
    | '/profile/goals'
    | '/profile/history'
    | '/profile/nudges'
    | '/profile/weight'
    | '/analysis/'
    | '/coach/'
    | '/community/'
    | '/profile/'
    | '/coach/workout/$sessionId/done'
    | '/coach/workout/$sessionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SignupRoute: typeof SignupRoute
  TutorialRoute: typeof TutorialRoute
  AnalysisResultRoute: typeof AnalysisResultRoute
  CoachChatRoute: typeof CoachChatRoute
  CommunityEventIdRoute: typeof CommunityEventIdRoute
  CommunityCreateRoute: typeof CommunityCreateRoute
  ProfileAchievementsRoute: typeof ProfileAchievementsRoute
  ProfileGoalsRoute: typeof ProfileGoalsRoute
  ProfileHistoryRoute: typeof ProfileHistoryRoute
  ProfileNudgesRoute: typeof ProfileNudgesRoute
  ProfileWeightRoute: typeof ProfileWeightRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
  CoachIndexRoute: typeof CoachIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  CoachWorkoutSessionIdDoneRoute: typeof CoachWorkoutSessionIdDoneRoute
  CoachWorkoutSessionIdIndexRoute: typeof CoachWorkoutSessionIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/': {
      id: '/coach/'
      path: '/coach'
      fullPath: '/coach/'
      preLoaderRoute: typeof CoachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/analysis'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/weight': {
      id: '/profile/weight'
      path: '/profile/weight'
      fullPath: '/profile/weight'
      preLoaderRoute: typeof ProfileWeightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/nudges': {
      id: '/profile/nudges'
      path: '/profile/nudges'
      fullPath: '/profile/nudges'
      preLoaderRoute: typeof ProfileNudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/history': {
      id: '/profile/history'
      path: '/profile/history'
      fullPath: '/profile/history'
      preLoaderRoute: typeof ProfileHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/goals': {
      id: '/profile/goals'
      path: '/profile/goals'
      fullPath: '/profile/goals'
      preLoaderRoute: typeof ProfileGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/achievements': {
      id: '/profile/achievements'
      path: '/profile/achievements'
      fullPath: '/profile/achievements'
      preLoaderRoute: typeof ProfileAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/reassess': {
      id: '/onboarding/reassess'
      path: '/reassess'
      fullPath: '/onboarding/reassess'
      preLoaderRoute: typeof OnboardingReassessRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/community/create': {
      id: '/community/create'
      path: '/community/create'
      fullPath: '/community/create'
      preLoaderRoute: typeof CommunityCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$eventId': {
      id: '/community/$eventId'
      path: '/community/$eventId'
      fullPath: '/community/$eventId'
      preLoaderRoute: typeof CommunityEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/chat': {
      id: '/coach/chat'
      path: '/coach/chat'
      fullPath: '/coach/chat'
      preLoaderRoute: typeof CoachChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/result': {
      id: '/analysis/result'
      path: '/analysis/result'
      fullPath: '/analysis/result'
      preLoaderRoute: typeof AnalysisResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/workout/$sessionId/': {
      id: '/coach/workout/$sessionId/'
      path: '/coach/workout/$sessionId'
      fullPath: '/coach/workout/$sessionId/'
      preLoaderRoute: typeof CoachWorkoutSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach/workout/$sessionId/done': {
      id: '/coach/workout/$sessionId/done'
      path: '/coach/workout/$sessionId/done'
      fullPath: '/coach/workout/$sessionId/done'
      preLoaderRoute: typeof CoachWorkoutSessionIdDoneRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingReassessRoute: typeof OnboardingReassessRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingReassessRoute: OnboardingReassessRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  SignupRoute: SignupRoute,
  TutorialRoute: TutorialRoute,
  AnalysisResultRoute: AnalysisResultRoute,
  CoachChatRoute: CoachChatRoute,
  CommunityEventIdRoute: CommunityEventIdRoute,
  CommunityCreateRoute: CommunityCreateRoute,
  ProfileAchievementsRoute: ProfileAchievementsRoute,
  ProfileGoalsRoute: ProfileGoalsRoute,
  ProfileHistoryRoute: ProfileHistoryRoute,
  ProfileNudgesRoute: ProfileNudgesRoute,
  ProfileWeightRoute: ProfileWeightRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
  CoachIndexRoute: CoachIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  CoachWorkoutSessionIdDoneRoute: CoachWorkoutSessionIdDoneRoute,
  CoachWorkoutSessionIdIndexRoute: CoachWorkoutSessionIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
